### ISSUE TITLE
move plugin config from separate file to the section of common plugins.ini

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_git_status#10]
@ildarkhasanshin can you help here?

**Comment by ildarkhasanshin** [comment]
ок, постараюсь

**Comment by Alexey-T** [comment]
сделал правки- не забудь сделать fetch from upstream

**Comment by Alexey-T** [comment]
@ildarkhasanshin сделаю это сам.

**Comment by ildarkhasanshin** [comment]
> сделаю это сам

ок
чем лучше хранить в plugins.ini?
или это постепенная миграция для старых плагинов с ini-настройками

**Comment by Alexey-T** [comment]
файл с 2 опциями. зачем плодить файлы? лучше в едином ини.
