### ISSUE TITLE
new dialog 'Git status'

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_git_status#14]
![Screenshot from 2022-04-13 12-35-30](https://user-images.githubusercontent.com/4154978/163147101-790c6b85-bcd1-456f-9bb0-b31956f91bfd.png)

1- read-only neeeded
2- button: align to the rigght / or to the center.
@ildarkhasanshin

**Comment by ildarkhasanshin** [comment]
https://github.com/CudaText-addons/cuda_git_status/pull/13/commits/8c9fee7dfc1bf94a3ce8d6bba59f7547699b5d01

**Comment by ildarkhasanshin** [comment]
почему-то ex0=True и ex1=True не срабатывают

**Comment by Alexey-T** [comment]
'ex0=True', 'ex1=True'

ЕМНИП, надо 'ex0=1', 'ex1=1'

**Comment by ildarkhasanshin** [comment]
https://github.com/CudaText-addons/cuda_git_status/pull/13/commits/1964394b8e34be75c3a3b436ab6fb468712b28c3

**Comment by ildarkhasanshin** [comment]
здесь подправить тогда нужно

https://wiki.freepascal.org/CudaText_API#dlg_custom_-_Properties_.22ex.22
`"edit", "memo":
"ex0": bool: read-only
"ex1": bool: font is monospaced
"ex2": bool: show border`

**Comment by Alexey-T** [comment]
done

https://wiki.freepascal.org/index.php?title=CudaText_API&diff=151745&oldid=151704
