### ISSUE TITLE
Checkout file

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_git_status#15]
![Screenshot from 2022-04-13 12-37-56](https://user-images.githubusercontent.com/4154978/163147509-bdd6814d-c73b-4fdf-85ce-a28277d6bae2.png)

1. yes/no -> ok/cancel
2. ~~don't forget MB_ICONnnnn~~
3. я не понял что вообще этот диалог преложил? git checkout значит "вытащить ветку такую-то и сделать ее активной". а git checkout file - что значит? 
@ildarkhasanshin

**Comment by ildarkhasanshin** [comment]
аналог git restore <file>
ок, переделаю на restore

**Comment by ildarkhasanshin** [comment]
https://github.com/CudaText-addons/cuda_git_status/pull/13/commits/ac71e9642f7efc7ef0c034cb6894c332f949b275
