### ISSUE TITLE
git popup menu

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_git_status#16]
@ildarkhasanshin Когда команда просто делает, то многоточине в конце не надо. (у тебя его нигде нет в названиях команд). А когда кмд что-то СПРОСИТ то надо. Проверь - если команда СПРОСИТ то есть многоточине в названии

**Comment by Alexey-T** [comment]
например Commit. оно же спросить коментарий? тогда "Commit..."

**Comment by ildarkhasanshin** [comment]
https://github.com/CudaText-addons/cuda_git_status/pull/13/commits/7cb0872c309a58f452296708559fdacbb4b816ef
