### ISSUE TITLE
git menu items - disable

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_git_status#17]
@ildarkhasanshin Я открыл файл из репо который без изменений. статусбар показывает без звезды. тогда зачем ты резрешил пункт git checkout file? и зачем commit если изменений нет?

можешь поставить disabled на пункты?

**Comment by CudaText-addons** [comment]
не надо наверное

**Comment by ildarkhasanshin** [comment]
почему? уже сделал

**Comment by Alexey-T** [comment]
а, ну тогда надо.
