### ISSUE TITLE
menu - dont create each time

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_git_status#18]
def callback_statusbar_click(self, id_dlg, id_ctl, data='', info=''):
        h = menu_proc(0, MENU_CREATE)

на каждый вызов меню. утечка!
сохраняй хендл меню в self.h_menu . 
@ildarkhasanshin

**Comment by ildarkhasanshin** [comment]
сделал

**Comment by Alexey-T** [comment]
не, не так надо.

1. задаем пониже строчки `class Command` поле в h_menu = None.
2. проверяем в коллбеке- оно Ноне или нет? если Ноне, то создаем меню и заполняем его! не надо делать MENU_CLEAR.

**Comment by Alexey-T** [comment]
3. записываем новый хендл после создания меню в  self.h_menu

**Comment by Alexey-T** [comment]
4. запоминаем хендлы двух menu items - тоже в self.h_menu_commit, self.h_menu_resstore - чтобы потом обращаться к ним и запрещать или разрешать пункты.

**Comment by Alexey-T** [comment]
```
if self.h_menu is None:
  self.h_menu = menu_proc(...CREATE...)
  # и тут же заполнение меню

# после if
menu_proc(...SHOW..)
```

**Comment by ildarkhasanshin** [comment]
https://github.com/CudaText-addons/cuda_git_status/pull/13/commits/6b3f049a18a163e3589366e8c2dfbcba0c917381
