### ISSUE TITLE
menu-show

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_git_status#19]
@ildarkhasanshin 

>MENU_SHOW: Shows given popup-menu. Only menu created with MENU_CREATE should be specified here. Param "command" must be tuple (x,y) or string "x,y" with screen-related coordinates, if empty - menu shows at mouse cursor.

тогда ты не должен читать позицию мыши. там дефолт нормальный

**Comment by ildarkhasanshin** [comment]
https://github.com/CudaText-addons/cuda_git_status/pull/13/commits/b7883d7e8cf7bb5613d9d82b0e1126bb9529c1eb
