### ISSUE TITLE
'Get log file' hangs

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_git_status#21]
зависает на минуту при вызове на файле plugins.json из https://github.com/Alexey-T/CudaText-registry/

**Comment by Alexey-T** [comment]
может там по кускам идет отчет? и просит ЕНТЕР?

**Comment by ildarkhasanshin** [comment]
ограничил -p -300

**Comment by Alexey-T** [comment]
тогда я не увижу весь лог? как -то не хорошо.

**Comment by CudaText-addons** [comment]
взял код
https://stackoverflow.com/questions/7736781/how-to-make-git-log-not-prompt-to-continue

**Comment by ildarkhasanshin** [comment]
у меня с такими параметрами все равно висит
до -300 еще нормально

**Comment by Alexey-T** [comment]
на каком репо и каком файле висит?

**Comment by ildarkhasanshin** [comment]
https://github.com/Alexey-T/CudaText-registry/
plugins.json

**Comment by Alexey-T** [comment]
у меня на этом фаайле дает Лог с 930 строкками. какое 1410?
последняя строка в логе-
937afbf0fc943a4633c2fe098584db60f4f50b41 rename files

**Comment by ildarkhasanshin** [comment]
а да 1410
у меня просто локально есть еще просто get log
т.е. все коммиты репо
вот там зависает

**Comment by CudaText-addons** [comment]
у меня не виснет, т.ч. не знаю чем помочь.
