### ISSUE TITLE
'commit' do not work??

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_git_status#26]
Ubuntu 20 x64

video --
[Kazam_00000.zip](https://github.com/CudaText-addons/cuda_git_status/files/8489295/Kazam_00000.zip)

@ildarkhasanshin

**Comment by Alexey-T** [comment]
Ildar,
в процессе видео видно что пропала панелька в стутусбаре и я не знал что делать! пока не повторил

**Comment by ildarkhasanshin** [comment]
git add history.txt
потом git commit -m '..' ведь

**Comment by Alexey-T** [comment]
теперь прошло.
Но! после add/ commit/ push - надо сбросить марки на гуттере и сбросить звезду в статусбаре!

**Comment by Alexey-T** [comment]
@ildarkhasanshin  fixed
