### ISSUE TITLE
status * for untracked files

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_git_status#30]
Куд репо имеет untracked files
```
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	../py/cuda_complete_html_text/
	../py/cuda_encode/

```
но это не должно давать показ звездочки в статусе!
@ildarkhasanshin

**Comment by Alexey-T** [comment]
надо вернуть код для gitmanager.is_dirty()

**Comment by Alexey-T** [comment]
fixed

**Comment by ildarkhasanshin** [comment]
но тогда возвращаемся к этой проблеме
https://ask-dev.ru/info/4315/how-do-i-programmatically-determine-if-there-are-uncommited-changes
git diff-index HEAD ... потерпит неудачу в ветки, в которой нет коммитов (например, в недавно инициализированном хранилище).

**Comment by Alexey-T** [comment]
не знаю что тут делать, т.к. не читал тот топик - может ты еще найдешь решение. но надо чтобы is_dirty было Ложь для моего случая.

**Comment by ildarkhasanshin** [comment]
https://github.com/CudaText-addons/cuda_git_status/pull/33

**Comment by ildarkhasanshin** [comment]
> есть untracked files

![image](https://user-images.githubusercontent.com/8765305/163703446-47a5d7f5-2b8e-4d8f-be25-0606828e597a.png)

**Comment by Alexey-T** [comment]
не понял. ты хочешь сделать как ВСКод что ли? а что он делает - не понял? мне НЕ надо чтобы untracked files добавлялись в репо. пусть они И БУДУТ торчать как untracked.
