### ISSUE TITLE
disable 'push' menu item

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_git_status#31]
@ildarkhasanshin как надо задавать enabled для push? при наличии коммита надо разрешать. а если еще нет комита, то запрещать. поищи плиз какие параметры это показывают.

**Comment by ildarkhasanshin** [comment]
https://github.com/CudaText-addons/cuda_git_status/pull/32/commits/9e82f0a7dd086d4cbc66050cfc68d87c087ef0b5
