### ISSUE TITLE
command "Show diff..."

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_git_status#35]
@ildarkhasanshin Мне бы лично пригодилось. я начал пользовать плагин! для мелких правок. если правка ОЧ мелкая сойдет то что уже есть. Но! если правки в 2-3-4 файлах сразу, то невозможно понять что именно ты запостиш в гит!!

чтобы это понять надо иметь запуск 'git diff' и его вывод показать в unix diff с лексером Diff.
уже счас это умеет делать плаг Show Unsaved Changes из коробки.

![Screenshot from 2022-04-19 15-45-14](https://user-images.githubusercontent.com/4154978/164007113-20967752-5547-4191-a877-800e3b5f16b3.png)

тут еще полезно то что я виду УДАЛЕННЫЕ строки.

**Comment by ildarkhasanshin** [comment]
ок, посмотрю Show Unsaved Changes

**Comment by Alexey-T** [comment]
да, тут бы еще придумать как из плагина - сделать push изменений в Н файлах сразу. в ком-строке я делаю так

сначала

    git diff

если все Окей-

    git commit -a -m "my cmt"
    git push

**Comment by Alexey-T** [comment]
@veksha Maybe you're interested :)

**Comment by veksha** [comment]
возможно придётся использовать
`git diff HEAD`
так как некоторые изменённые файлы мы могли уже добавить в индекс (пункт меню Add file... или git add), а некоторые ещё нет.

**Comment by Alexey-T** [comment]
в любом случае, я это не делаю, и патчи будут расмотрены.

**Comment by ildarkhasanshin** [comment]
> уже счас это умеет делать плаг Show Unsaved Changes из коробки.

не найду
ссылку бы

**Comment by CudaText-addons** [comment]
вот она -
https://github.com/Alexey-T/CudaText/tree/master/app/py/cuda_show_unsaved

**Comment by veksha** [comment]
вместо этого всего можно просто вызывать git-gui, почему нет.
или как дополнительный пункт меню.
