### ISSUE TITLE
trying to do commit nothing happens, got no error

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_git_status#37]
tried from cmd.exe and turns out it was "Author identity unknown" error.

<details>
  <summary>Author identity unknown</summary>
  
```
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
```
</details>

we can do something like this to print errors to console:
<details>
  <summary>patch</summary>

```diff
diff --git a/git_manager.py b/git_manager.py
index bd2293c..310a2d5 100644
--- a/git_manager.py
+++ b/git_manager.py
@@ -22,6 +22,7 @@ class GitManager:
             p = subprocess.Popen(cmd,
                                  stdin=subprocess.PIPE,
                                  stdout=subprocess.PIPE,
+                                 stderr=subprocess.PIPE,
                                  cwd=cwd,
                                  startupinfo=startupinfo)
         else:
@@ -31,11 +32,16 @@ class GitManager:
             p = subprocess.Popen(cmd,
                                  stdin=subprocess.PIPE,
                                  stdout=subprocess.PIPE,
+                                 stderr=subprocess.PIPE,
                                  cwd=cwd,
                                  env=my_env)

         #p.wait() # this makes deadlock if process gives lot of data, it's documented in Python docs
-        stdoutdata, _ = p.communicate()
+        stdoutdata, stderrdata = p.communicate()
+        error_text = stderrdata.decode('utf-8')
+        if 'Author identity unknown' in error_text:
+            print("Git Status error: " + error_text)
+
         ''' #debug
         if stdoutdata:
             print('Git for:', repr(args), ', gets:', stdoutdata)
```

</details>

**Comment by Alexey-T** [comment]
>trying to do commit nothing happens

I do this in plugin

- Add file (add file to staged)
- Commit
- Push

>Author identity unknown

Git needs your identity. why don't you run these commands in terminal?

**Comment by veksha** [comment]
> Git needs your identity. why don't you run these commands in terminal?
i will. just wanted to point out that plugin can be improved to show some errors in console rather then just be silent.

**Comment by Alexey-T** [comment]
agreed. commited. will publish the plugin little later. Tks.

**Comment by Alexey-T** [comment]
Not sure how that multiline error wil look in the console. :)_

**Comment by veksha** [comment]
if it's ugly, we can do one line `print("Git Status error: Author identity unknown. Please configure your user.name and user.email for git")`

**Comment by veksha** [comment]
if "who you are" in error_text ?

**Comment by Alexey-T** [comment]
fixed it now for my error-text. commited.

**Comment by veksha** [comment]
it works!
but we can make it universal for all fatal errors. (if 'fatal:')

for example `fatal: empty ident name (for <>) not allowed`
and others. (fatal: not a git repository, etc..)

**Comment by veksha** [comment]
or even if error_text is not empty then print it to console.

**Comment by Alexey-T** [comment]
Ok, done as suggested. "if error_text:"

**Comment by Alexey-T** [comment]
```
        # don't always show error_text, it may be normal message for 'push' action
        if '\nfatal: ' in error_text:
            print("NOTE: Git Status: ", error_text)
```
fixed
