### ISSUE TITLE
slow status bar icon

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_git_status#38]
Это у всех git иконка в строке состояния медленно появляется при старте и при переключении вкладок или только у меня?
Если у всех, то попробуйте этот патч и скажите или скорость выросла. ещё понять бы почему так происходит.
```diff
diff --git a/__init__.py b/__init__.py
index 0d82616..2bd4755 100644
--- a/__init__.py
+++ b/__init__.py
@@ -163,7 +163,7 @@ class Command:
         """ * check if thread returned new badge
             * stop timer if thread is done
         """
-
+        time.sleep(0.08)
         if not self.badge_results.empty(): # have new badge
             _fn, _badge = self.badge_results.get()
             self.update(_fn, _badge)
```

**Comment by Alexey-T** [comment]
Hmm, I don't know, sorry :)

**Comment by Alexey-T** [comment]
проверил. без пача - иконка ( и инфо) кажется через 1 сек после старта.
с пачем - сразу.
пока не понятно "как ето работает" и почему именно 0.08.

**Comment by veksha** [comment]
существует ли возможность использовать какой-нибудь профайлер для питона при запущенной(-ом) Cud'е?
какие доступны удобные средства дебага у встроенного питона кроме print?

я с питоном не очень близко знаком. возможно потоки управляются каким-то хитрым глобальным механизмом. если да, то как на него влиять?

**Comment by Alexey-T** [comment]
кроме print - модуль logging (который все равно сделает print). https://docs.python.org/3/howto/logging.html

>возможно потоки управляются каким-то хитрым глобальным механизмом. если да, то как на него влиять?

потоки я еще не изучал.

**Comment by veksha** [comment]
к где посмотреть как работает  timer_proc ?
как реализовано внутри?

> timer_proc(TIMER_START, TIMERCALL, 70)

**Comment by Alexey-T** [comment]
в сорсах это - в formmain_py_api.inc, 
```
      case NIdAction of
        TIMER_START,
        TIMER_START_ONE: 
```

**Comment by veksha** [comment]
this change seem to give git icon the maximum speed.

```diff
-        if not self.badge_results.empty(): # have new badge
-            _fn, _badge = self.badge_results.get()
-            self.update(_fn, _badge)
+        #if not self.badge_results.empty(): # have new badge
+        _fn, _badge = self.badge_results.get()
+        self.update(_fn, _badge)

```

can you test it, @Alexey-T  ?

PS:
i noticed another thing. plugins can affect each other somehow.
try this:
1. install Terminal+ (and click on it's icon to make it automatically be shown on Cuda start)
2. install git_status
3. open some file (must be inside git rep) and set ui_repopen_session=true
4. restart.
git_status icon is not showing up at all! what is happened?? Opened terminal+ and opened file on Cuda's start affects git_status somehow. it will stuck on p.communicate() procedure for some reason.
it's hard to debug for me.

**Comment by Alexey-T** [comment]
>this change seem to give git icon the maximum speed.

Applied. seems it cannot slow down, because code is already in on_timer..

**Comment by Alexey-T** [comment]
what is happening with 2 plugins? they both run processes. Terminal+ runs Bash (or another one), GitStatus runs Git. maybe one of plugins does it wrong... you see code stuck in subprocess code (comminicate)? maybe some python issue?

**Comment by veksha** [comment]
> maybe some python issue

is it possible to try different embedded python version with Cuda?
if it's a bug in python it could be fixed already in newer versions.
do I need to replace some files or recompile pascal code?

**Comment by Alexey-T** [comment]
The info
https://wiki.lazarus.freepascal.org/CudaText#Python_on_Windows
