### ISSUE TITLE
disable menu item

### ISSUE THREAD

**Issue by CudaText-addons** [CudaText-addons/cuda_git_status#42]
@veksha 
why not to disable the menuitem for current branch, not only mark it with a mark?

**Comment by veksha** [comment]
i tried that and it looks ugly on Windows.

**Comment by veksha** [comment]
![image](https://user-images.githubusercontent.com/275333/171329453-ee438c20-bf60-41bb-b93e-7d1a7b77a0b0.png)

interesting how it looks on other OS'es.
disabled look "feels" like we have no access to that branch. :)

**Comment by CudaText-addons** [comment]
why ugly? it looks normal - usual item which we can;t choose,
