### ISSUE TITLE
logging for tests

### ISSUE THREAD

**Issue by CudaText-addons** [CudaText-addons/cuda_git_status#54]
@veksha can you add usage of 'logging' module, and a global var (bool) which enablees/disables logging to file?
log messages:

- just before running process of git
- just after the process closed (after p.communicate?)

we need log to file with file flashing to disk.
so I can change that global var to True, and test my local freezes, and see logfile

**Comment by veksha** [comment]
another thing you can try is untick this checkbox "win32 gui application":

![image](https://user-images.githubusercontent.com/275333/171992010-cb94fbc1-0617-4bf5-9520-e6cb4ddd129b.png)

then redirect stdout/err back to defaults:
```python
import sys
sys.stdout = sys.__stdout__
sys.stderr = sys.__stderr__
```

now you will able to see all prints in terminal even after application will freeze or crash.

I'm not familiar with 'logging' module. can't do it quick.

**Comment by Alexey-T** [comment]
Ok, I will add it in local test

**Comment by veksha** [comment]
@Alexey-T , have you experienced bugs with cuda_git_status lately?
Like git actions was performed for wrong repository? (diff window for wrong repository, or strange log messages from git_status)

**Comment by Alexey-T** [comment]
Nope...

**Comment by veksha** [comment]
@Alexey-T, do you still have freezes? do you need logging?

**Comment by Alexey-T** [comment]
Nope, I don't need logging.

**Comment by veksha** [comment]
can be closed?
