### ISSUE TITLE
cwd is correct?

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_git_status#59]
@veksha 
```

    def run_git(self, args, silence_errors=False):
        self.last_error = ''
        cmd = [self.git] + args
        cwd = self.getcwd()
```
do we have always the OK cwd param ? we want to have here what - the folder of Git repo (containing .git)? but we don't calculate this dir, no?

**Comment by veksha** [comment]
``` python
def getcwd(self):
        f = self.filename
        cwd = None
        if f:
            cwd = os.path.dirname(f)
        return cwd
```

sometimes `self.filename` can be empty. i got this bug in the past, but I forgot how to reproduce it.

**Comment by veksha** [comment]
we want to have here folder of current file
