### ISSUE TITLE
commiting of deleted files not supported yet

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_git_status#60]
we can have 2 situations:
1. some deleted files and some changes in other files.
2. only some deleted files, no other changes.

what should we do?
 - we can enable `Commit...` menu item in situation 2 and when this item is clicked just add-and-commit all deletions.
 - in situation 1 we can __silently__ add all deletions to next commit along with other changes (when `Commit...` is clicked)
   or  we can show confirmation message box like "some files were deleted, do you want to commit these deletions as well?"
 - ....
 - your variants

**Comment by Alexey-T** [comment]
Does terminal cmd “git commit” use deletions? Or do we need to do “git add -A”?

**Comment by veksha** [comment]
to add file deletion to staging area (index) we just use `git add subdir/deleted_file.py` because git still tracks this file-path even though the file is not present on disk. (after committing this deletion the file will be untracked completely I think).

we can use `git diff --summary` to see if there are any file deletions made by user (it can be rename or file move as well, all cases showed as "delete"):

```console
$ git diff --summary
 delete mode 100644 deleted_file.py
 delete mode 100644 subdir/deleted_file2.py
```

```
--summary
Output a condensed summary of extended header information such as creations, renames and mode changes.
```

`git diff --summary` is not showing anything except for unstaged file deletions (or mode changes). so this is useful command.
we are interested in deletions and not mode changes for now. so we filter this output list by first word "delete ".
we can store this list in some variable like `list_deleted` inside `callback_statusbar_click` procedure and.. do something with it.

**Comment by Alexey-T** [comment]
that is a good suggestion (plan).

**Comment by veksha** [comment]
i have no idea how to implement this in `cuda_git_status`, but users can now use `cuda_hotspots` plugin to deal with deleted files.
so this issue is solved like this for now.
