### ISSUE TITLE
autocompletion dialog shows in another tab

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_git_status#63]
> BTW: autocompletion dialog shows too... same type of bug! I will look into it.

hmm.. maybe it's a bug in pascal code?
I have `autocomplete_autoshow_chars: 2`

1. start typing a lot of random chars in a file with no LSP (no lexer!)
2. **quickly** change tab to the one with LSP/lexer and where caret is placed on some line where autocompletion can have some results.

reproduces, @Alexey-T ?

_Originally posted by @veksha in https://github.com/CudaText-addons/cuda_git_status/issues/62#issuecomment-1286513159_

**Comment by veksha** [comment]
(not a git_status issue but.. we can discuss it here)

**Comment by Alexey-T** [comment]
no repro on linux.

**Comment by veksha** [comment]
try to add print to `lsp.py` like on video:

0. set `autocomplete_autoshow_chars: 2`
1. create tab with Python and "p" char and caret after "p".
2. create empty tab
3. inside empty tab type something and quickly switch to Python tab
4. you will see "on_complete" message and autocompletion listbox

https://user-images.githubusercontent.com/275333/197328353-6081dd01-2ccf-4b1b-835b-6ae7c4be0899.mp4

**Comment by Alexey-T** [comment]
Thanks. some issue with timer (many commands don't run immediately, but via timer). to see

**Comment by veksha** [comment]
maybe "autocomplete_autoshow_chars" functionality has some timer (delay) ?
if there is a delay, can we minimize it?
also on tab switch this timer/event can be stopped/discarded. (for on_complete)

**Comment by Alexey-T** [comment]
fixed. please test (I tested)

**Comment by veksha** [comment]
works! thanks
