### ISSUE TITLE
themed color

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_git_status#7]
@ildarkhasanshin 

how to get themed color:
```
d = app_proc(PROC_THEME_SYNTAX_DICT_GET, '')
MY_DECOR_COLOR = d['LightBG3']['color_back']
```

**Comment by ildarkhasanshin** [comment]
https://github.com/CudaText-addons/cuda_git_status/pull/6/commits/5e991301507919851bc6e74a72fad5db7d951381
