### ISSUE TITLE
warning icon for "Restore file" action.

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_git_status#70]
let's change this msgbox icon? (and maybe capitalize "REALLY")

![image](https://github.com/CudaText-addons/cuda_git_status/assets/275333/487a1f94-e0b7-4d8c-9f4a-1cf51841f81e)

how i prefer:

![image](https://github.com/CudaText-addons/cuda_git_status/assets/275333/07918685-4e9e-4531-9cfb-2cd9e9e7e0e5)

**Comment by Alexey-T** [comment]
Agree!

**Comment by Alexey-T** [comment]
Done

**Comment by veksha** [comment]
thanks!
