### ISSUE TITLE
`commit` menu item and `commit/amend` menu item are incorrectly enabled/disabled

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_git_status#71]
@ildarkhasanshin @Alexey-T 

i think `commit` menu item and `commit/amend` menu item are incorrectly enabled/disabled.

1. `commit` enables when `(dirty and list_staged) or no_commits_yet)` is True, which is strange. I can have empty repo with nothing staged and `commit` will be enabled. maybe leave only `list_staged` here?

2. `commit/amend` menu item is almost never enabled when needed. it enables when `unpushed_info` is non zero (why? what is the logic here?), but i think it should be enabled always. `amend` can add staged files to the last commit or it can just change it's message (when nothing is staged), always useful.

(also without `unpushed_info` call, `is_dirty` and `run_git(["status"])` call we can save ~0.26 sec of menu popup time.)

https://github.com/CudaText-addons/cuda_git_status/blob/ec61337f0a7010fc82c14349f7bdee6b828edffb/__init__.py#L307-L314

**Comment by Alexey-T** [comment]
I do not know why enabled states are so. I never used commit/amend so it's not my code. let's fix.

**Comment by veksha** [comment]
PR: https://github.com/CudaText-addons/cuda_git_status/pull/72

**Comment by Alexey-T** [comment]
testing.

- made update of Cud's history.txt
- 'edit prev commit' is enabled-- ok, changed comment to 'history.txt'
- push is not enabled now, so how can I push changed commit-msg? 
- and statusbar shows now 'master-1+1'. what?

**Comment by veksha** [comment]
you changed commit that was already pushed., so remote history and local history is now different. this is OK most of the time.
in this case you should just do "git push --force" (this command is present if Command Palette)

**Comment by veksha** [comment]
we can also add "push --force" to git_status context menu in such situations (when history diverges and you see `-1+1`)

**Comment by Alexey-T** [comment]
so it is ok. 'git push (forced)' worked. solved.

**Comment by CudaText-addons** [comment]
PR applied.
