### ISSUE TITLE
work with decor tag

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_git_status#8]
ed.decor(DECOR_SET, line=l, tag=l,

работа с ТЕГом такая. 

- берешь новое значение тега MY_TAG из PROC_GET_UNIQUE_TAG - один раз!
- ставишь тег для всех вызовов DECOR_SET
- сначала удаляешь все декоры с твоим тегом - DECOR_DELETE_BY_TAG

@ildarkhasanshin

**Comment by ildarkhasanshin** [comment]
для чего DECOR_DELETE_BY_TAG
если в ed.decor(.., auto_del=True)

**Comment by Alexey-T** [comment]
auto_del - удалять декоры при удалении текста. 
"auto_del": bool, auto-delete decoration, when its line is deleted.

а тебе надо после правки очистить все декоры вообще

**Comment by ildarkhasanshin** [comment]
https://github.com/CudaText-addons/cuda_git_status/pull/6/commits/09c54eac8bc3f3d42ad1b71a8c7b3deb7087719d
так?

**Comment by ildarkhasanshin** [comment]
https://github.com/CudaText-addons/cuda_git_status/pull/6/commits/8feb62496eb97eeafc234251c3aa8e8f87d28066

**Comment by Alexey-T** [comment]
DIFF_TAG еще радо юзать при добавлении всех декоров DECOR_SET

**Comment by Alexey-T** [comment]
ed.decor(DECOR_DELETE_BY_TAG) 
- нет! ты не указал тут tag=DIFF_TAG.

**Comment by ildarkhasanshin** [comment]
https://github.com/CudaText-addons/cuda_git_status/pull/6/commits/a1dfcfe2ace00a98635ee009cef0716923d1d9dc

**Comment by Alexey-T** [comment]
завтра сделаю merge.  потести у себя.
