### ISSUE TITLE
api ver

### ISSUE THREAD

**Issue by Alexey-T** [CudaText-addons/cuda_git_status#9]
давай требовать новое АПИ 1.0.420 в .inf
@ildarkhasanshin

**Comment by ildarkhasanshin** [comment]
что именно?

добавить в plugins.ini
[events]
cuda_git_status=on_change_slow
?

**Comment by ildarkhasanshin** [comment]
https://github.com/CudaText-addons/cuda_git_status/pull/6/commits/d5dff75df0ff64fc05e5eb459c7fdd8377074bc3
